"""
This module defines the URL routes for the Issues and Comments in this Django app.

It includes routes for the IssuesViewSet and CommentsViewSet.
The routes are automatically generated by a router.
"""

from django.urls import path, include
from rest_framework import routers
from rest_framework_nested import routers as nested_routers
from projects.views import ProjectViewSet
from .views import IssuesViewSet, CommentsViewSet

router = routers.DefaultRouter()
router.register(r'projects', ProjectViewSet, basename='project')

issues_router = nested_routers.NestedDefaultRouter(router, r'projects', lookup='project')
issues_router.register(r'issues', IssuesViewSet, basename='project-issues')

comments_router = nested_routers.NestedDefaultRouter(issues_router, r'issues', lookup='issue')
comments_router.register(r'comments', CommentsViewSet, basename='issue-comments')

urlpatterns = [
    path('', include(issues_router.urls)),
    path('', include(comments_router.urls)),
]
