# Generated by Django 5.0.1 on 2024-02-01 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={},
        ),
    ]
