# Generated by Django 5.0.1 on 2024-02-01 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='can_assign_issues',
        ),
    ]
