# Generated by Django 5.0.1 on 2024-02-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_contributor_can_assign_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('can_view', 'Can_View'), ('can_edit', 'Can_Edit'), ('can_delete', 'Can_Delete')], default='can_view', max_length=20),
        ),
    ]
